apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo2-deployment
  namespace: quickstart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:4.4.10
          envFrom:
            - secretRef:
                name: mongo-secret
          ports:
            - containerPort: 27017
